# This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.

#          -                   |
#24- 12- 12- 12C2 12- 12D2 12-    35G2 1- 11C2 1-   36B2 12C3
24- 12- 12- 12C2 12- 12D2 12-    12G2 12- 12E2 12-  36B2 12C3
#          -                   |
47D3 1-     12D3 12G3 12-  12B2  12C3 12D3 12- 12F3 48G3

[aaa=96]
[sleep:=aaa*(24+24+8-4)]
<sleep>-
