# This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.

#                           |
12D5 12G5 24- 24- 12G5 12-     12G5 12B5 24- 12B5 12B5 12- 12G5
#                           |
48B5          24A5  24G5       48F5 24-               12F5 12E5

#                           |
96D5                           84E5                        12C5
#                           |
96E5                           96G5

#                           |
96F5                           96F5
#                           |
96G5                           48B4               48G4
