# This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.

#                           |
12B4 12D5 24- 24- 12B4 12-     12D5 12G4 24- 12G4 12D4 12- 12B3
#                           |
24D4   48G4        24B4        48C5 24-               12B5 12C5

#                           |
24B4   24A4  24G4  12F4 12E4  12- 12D4 12- 12C4 12- 12B3 12- 12A3
#                           |
48C4          48G4            48B3           48F4

#                           |
96C4                          96A3
#                           |
96B3                          96D4
